# -*- coding: utf-8 -*-
"""X Sentiment_Analysis

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1GqnsD_jiJC8DPn6fMi6WZQ6-bm5bML4h
"""

!nvidia-smi

import tensorflow as tf

print(tf.config.list_physical_devices('GPU'))

from google.colab import files

uploaded = files.upload()

import pandas as pd

columns = [
    'sentiment',
    'id',
    'date',
    'query',
    'user',
    'text'
]

df = pd.read_csv(
    '/content/training.1600000.processed.noemoticon.csv',
    encoding='latin-1',
    names=columns
)

print(df.shape)
df.head()

df = df[['text', 'sentiment']]

df['sentiment'] = df['sentiment'].replace({
    4: 1
})

print(df.head())
print(df['sentiment'].value_counts())

import re

def clean_text(text):
    text = str(text).lower()
    text = re.sub(r"http\S+", "", text)
    text = re.sub(r"@\w+", "", text)
    text = re.sub(r"[^a-zA-Z\s]", "", text)
    text = re.sub(r"\s+", " ", text).strip()
    return text

df["clean_text"] = df["text"].apply(clean_text)

df[["text", "clean_text"]].head()

df_small = df.sample(
    n=100000,
    random_state=42
)

print(df_small.shape)

from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    df_small['clean_text'],
    df_small['sentiment'],
    test_size=0.2,
    random_state=42
)

print(X_train.shape)
print(X_test.shape)

print(y_train.shape)
print(y_test.shape)

from tensorflow.keras.preprocessing.text import Tokenizer

MAX_WORDS = 10000

tokenizer = Tokenizer(num_words=MAX_WORDS)

tokenizer.fit_on_texts(X_train)

print(len(tokenizer.word_index))

print(tokenizer.word_index['love'])

print(list(tokenizer.word_index.items())[:10])

X_train_seq = tokenizer.texts_to_sequences(X_train)

X_test_seq = tokenizer.texts_to_sequences(X_test)

print(X_train.iloc[0])
print(X_train_seq[0])

from tensorflow.keras.preprocessing.sequence import pad_sequences

X_train_pad = pad_sequences(
    X_train_seq,
    maxlen=20,
    padding='post'
)

X_test_pad = pad_sequences(
    X_test_seq,
    maxlen=20,
    padding='post'
)

X_train_pad.shape

from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding, LSTM, Dense

model = Sequential([
    Embedding(10000, 64),
    LSTM(
        32,
        dropout=0.2,
        recurrent_dropout=0.2
    ),
    Dense(1, activation='sigmoid')
])

model.build(input_shape=(None, 50))

model.summary()

model.compile(
    optimizer='adam',
    loss='binary_crossentropy',
    metrics=['accuracy']
)

from tensorflow.keras.callbacks import EarlyStopping

early_stop = EarlyStopping(
    monitor='val_loss',
    patience=2,
    restore_best_weights=True
)

history = model.fit(
    X_train_pad,
    y_train,
    epochs=20,
    batch_size=128,
    validation_split=0.2,
    callbacks=[early_stop]
)

sample = ["virat kohli played an amazing innings today"]

sample_clean = [clean_text(text) for text in sample]

sample_seq = tokenizer.texts_to_sequences(sample_clean)

sample_pad = pad_sequences(
    sample_seq,
    maxlen=20,
    padding='post',
    truncating='post'
)

prediction = model.predict(sample_pad)

print(prediction)

if prediction[0][0] >= 0.5:
    print("Positive 😊")
else:
    print("Negative 😞")

samples = [
    "good",
    "not good",
    "very good",
    "excellent",
    "terrible",
    "not terrible",
    "i love this",
    "i do not love this"
]

sample_clean = [clean_text(text) for text in samples]

sample_seq = tokenizer.texts_to_sequences(sample_clean)

sample_pad = pad_sequences(
    sample_seq,
    maxlen=20,
    padding='post',
    truncating='post'
)

prediction = model.predict(sample_pad)

print(prediction)

if prediction[0][0] >= 0.5:
    print("Positive 😊")
else:
    print("Negative 😞")

print(df['clean_text'])

df[df['clean_text'].str.contains('not happy', na=False)].head()

